# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    container_name: db
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: schueler
      MARIADB_USER: leo
      MARIADB_PASSWORD: schueler
    volumes:
      - ./mysql:/var/lib/mysql
  
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080